= Changelog
:toc:

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].




[appendix]
== Extra notes

* v0.1.1 has been versioned without any changes due to (speculated) GitHub caching with the `go.mod` file affecting the fetching of the Hugo module.




== Unreleased


=== Updated

* Update class names of several components.

** `.icon` has been updated to `.site__icon`.
** `.list` has been updated to `.site__list`.

* Update the icon template.
This is also useful for those who are extensively modifying the theme.





== [0.6.0] - 2023-03-16


=== Added

- Proper site layout for right-to-left (RTL) direction.

- Color palette for `::backdrop` pseudo-element.
It apparently doesn't inherit from the root so we'll have to create it ourselves.


=== Updated

- Update Hugo module for Simple Icons to v8.7.0.


=== Fixed

- Use gaps for certain components.
This also happens to properly style for RTL at the cost of good-looking separators.
I'll just find an alternative for that.




== [0.5.0] - 2023-02-27


=== Removed

- External links styling.
Now that it stayed in the theme for some time, I realized it isn't worth to implement it.
It just adds clutter and setting it up to work properly is a bit too much compared to what you would get.
Most users would probably use some font froms Google Fonts which most of them are missing the required glyph from my non-scientific testing.
So yeah, not worth it.


=== Updated

- Reduce unnecessary rules in the site stylesheet.
Pretty standard stuff.

- Update styling for content spacing.
It should be more consistent when changed with the font size.


=== Fixed

- Conditional rendering for the site post metadata.
This enables non-content pages (i.e., "About" pages, "Contact" pages).




== [0.4.2] - 2023-02-27


=== Updated

- Update the table styling.

- Make component selection style consistent.


=== Fixed

- Remove the overridden selection (i.e., `::selection`) style.
It is harder to configure it right for accessibility plus it isn't recommended to add one anyways.

- Fix the style for `<code>` elements.




== [0.4.1] - 2023-02-24


=== Fixed

- Revert the site layout.

- Update the datetime string for the appropriate components.




== [0.4.0] - 2023-02-24


=== Added

- Accessibility tags for certain elements in the website (i.e., `<hr>` in non-content).


=== Updated

- Reposition certain components.
This is to (hopefully) fix certain layouts when the article is read in reader mode (in major web browsers such as Chrome and Firefox).

- Spacing between basic elements (i.e., `<p>`).

- Responsive font sizing.




== [0.3.4] - 2022-11-28


=== Fixed

- Fix `<head>` layout.

- Fix permalink for favicons.




== [0.3.3] - 2022-11-22


=== Fixed

- Limit external link styling only to article content boxes.
This is to limit stomping on custom site styles that often customize outside of the content.

- Fix layout on section pages.

- Correct stylesheet appending order.




== [0.3.2] - 2022-11-12


=== Added

* References to favicons with `favicon.png`. footnote:[Somehow, I forgot about that.]

=== Changed

* Make external links styling site-wide.
Now only certain parts should only have the links unstyled.


=== Fixed

* Fixes to Heroicon template.
This should fix a bug involving missing icons.

* Unstyling to internal links.




== [0.3.1] - 2022-10-24


=== Fixed

- Heroicons integration. footnote:[This is what I get for doing things at night. Before sleep.]




== [0.3.0] - 2022-10-23


=== Added

* Indicator for the selected theme in the dropdown menu.

* External link styling.


=== Updated

* Minimum Go runtime version in `go.mod`.
This is more like someone forgot to update it from the previous release but pay no mind for it. footnote:[Since recent Hugo versions require Go v1.16 at minimum, anyways. ;p]

* Update link:https://github.com/foo-dogsquared/hugo-mod-web-feeds[Simple Icons Hugo module] to v7.16.0.

* Update Heroicons to 2.x.x.

* The code block has maximum height for half the height of the viewport (`50vh`).

* More consistent theming for the content text.

* More styling for paged media.

* Cleaner formatting for tables.




== [0.2.0] - 2022-05-04

=== Changed

* Increase the minimum version required to v0.95.0 due to using much of the new features found on the release.

* Clean the layouts.

* Change the style of the horizontal rule with colors.

* The theme button is placed in the site header instead of the top-rightmost side of the viewport.

* Update the link:https://github.com/foo-dogsquared/hugo-mod-simple-icons[Simple Icons module] to v6.19.0.

* Update link:https://heroicons.com/[Heroicons module] to v1.0.6.

* Improve the list template to be more considerable to easy eyeing of the posts.

* Fallback themes are now enforced to be implemented into two themes: one for light and one for dark theme.
This is changed from a single `+_index+` Base16 scheme to `+_{dark,light}+` Base16 scheme.
The Hugo theme also has fallbacks for certain cases.

** If the user gives only one system theme, the Hugo theme will generate the appropriate counterpart theme.
E.g., if there is only `+_dark+`, the Hugo theme will generate the light theme.

** If given neither, fallback themes will be used.

* Replace Travis CI with GitHub workflows.


=== Fixed

* Fix the site authors with its documentation.

* Format the files correctly as specified from the EditorConfig file.


=== Removed

* Setting the default theme with `+./data/more-contentful/themes/_index.{yaml,json,toml}+`.
It has been replaced with setting system themes with `+./data/more-contentful/themes/_{light,dark}.{yaml,json,toml}+`.




== [0.1.3] - 2020-11-06

=== Changed

* All references to `.Date` are changed with `.PublishDate` as it is more reliable.
The `.PublishDate` can be manually set with the `publishdate` frontmatter variable and if unset, it is the assumed to be the `date` variable.

* Link color into `base0C`.

* Update Simple Icons Hugo module.

* Update the original theme Hugo module.


=== Fixed

* Make a few tweaks with CSS.
* Formatting of files.
* Relative files in the contact links are now linked with `absLangURL` which is useful for linking web feeds.




== [0.1.2] - 2020-11-04

=== Fixed

* The page titles inside of `<title>` has been updated similarly to https://gohugo.io/[Hugo's way of titling pages].
* Caching issue for the theme which causes a variety of unexpected behavior to pop up:
** The inability to update the theme stylesheet and the theme button component.
** The incorrect page titles.




== [0.1.0] - 2020-11-02

The initial release.


=== Added

* Easy custom color schemes with https://github.com/chriskempson/base16[Base16 scheme files].
* Social media icons with https://github.com/simple-icons/simple-icons[Simple Icons] with the added setting to set whether it should appear in text or as an icon.
* Icons on the content metadata for easier reading with link:https://heroicons.com/[HeroIcons].


=== Changed

* Port CSS into SCSS now requiring the theme to be used with the extended version.

* Revamp the appearance of the site.

* Update the theme button with multiple theme selection.
Since the theme now supports more than two themes, the https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme[`prefers-color-scheme`] (the automagic color scheme solution) will not be used.
footnote:[Workarounds exist to let automatic and manual color scheme selection work together but it is not worth it for now.]

* The content metadata in the single content format.
** Move to the bottom of the content to make more room for other metadata and to make the content more above-the-fold.
Incidentally, this makes the theme more suitable for personal blogs (which is fine to me).
** With the metadata has been moved, it is now replaced with the same metadata section as seen from the list template.

* Improve conditional display of the table of content.

* Change "Back to home" with a link bringing to the top of the page instead.

