= Changelog
:toc:

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].




[appendix]
== Extra notes

* v0.1.1 has been versioned without any changes due to (speculated) GitHub caching with the `go.mod` file affecting the fetching of the Hugo module.




== Unreleased

=== Changed

* Increase the minimum version required to v0.95.0 due to using much of the new features found on the release.

* Clean the layouts.

* Change the style of the horizontal rule with colors.

* The theme button is placed in the site header instead of the top-rightmost side of the viewport.

* Update the link:https://github.com/foo-dogsquared/hugo-mod-simple-icons[Simple Icons module].
For reference, it is from link:https://github.com/simple-icons/simple-icons/commit/6f83d1dd85662360353c73d42c6b6b4ca75d6e14[this commit].

* Improve the list template to be more considerable to easy eyeing of the posts.

* Fallback themes are now enforced to be implemented into two themes: one for light and one for dark theme.
This is changed from a single `_index` Base16 scheme to `_{dark,light}` Base16 scheme.
The Hugo theme also has fallbacks for certain cases.

** If the user gives only one system theme, the Hugo theme will generate the appropriate counterpart theme.
E.g., if there is only `_dark`, the Hugo theme will generate the light theme.

** If given neither, fallback themes will be used.


=== Fixed

* Fix the site authors with its documentation.

* Format the files correctly as specified from the EditorConfig file.


== Removed

* Setting the default theme with `./data/more-contentful/themes/_index.{yaml,json,toml}`.
It has been replaced with setting system themes with `./data/more-contentful/themes/_{light,dark}.{yaml,json,toml}`.




== [0.1.3] - 2020-11-06

=== Changed

* All references to `.Date` are changed with `.PublishDate` as it is more reliable.
The `.PublishDate` can be manually set with the `publishdate` frontmatter variable and if unset, it is the assumed to be the `date` variable.

* Link color into `base0C`.

* Update Simple Icons Hugo module.

* Update the original theme Hugo module.


=== Fixed

* Make a few tweaks with CSS.
* Formatting of files.
* Relative files in the contact links are now linked with `absLangURL` which is useful for linking web feeds.




== [0.1.2] - 2020-11-04

=== Fixed

* The page titles inside of `<title>` has been updated similarly to https://gohugo.io/[Hugo's way of titling pages].
* Caching issue for the theme which causes a variety of unexpected behavior to pop up:
** The inability to update the theme stylesheet and the theme button component.
** The incorrect page titles.




== [0.1.0] - 2020-11-02

The initial release.


=== Added

* Easy custom color schemes with https://github.com/chriskempson/base16[Base16 scheme files].
* Social media icons with https://github.com/simple-icons/simple-icons[Simple Icons] with the added setting to set whether it should appear in text or as an icon.
* Icons on the content metadata for easier reading with link:https://heroicons.com/[HeroIcons].


=== Changed

* Port CSS into SCSS now requiring the theme to be used with the extended version.

* Revamp the appearance of the site.

* Update the theme button with multiple theme selection.
Since the theme now supports more than two themes, the https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme[`prefers-color-scheme`] (the automagic color scheme solution) will not be used.
footnote:[Workarounds exist to let automatic and manual color scheme selection work together but it is not worth it for now.]

* The content metadata in the single content format.
** Move to the bottom of the content to make more room for other metadata and to make the content more above-the-fold.
Incidentally, this makes the theme more suitable for personal blogs (which is fine to me).
** With the metadata has been moved, it is now replaced with the same metadata section as seen from the list template.

* Improve conditional display of the table of content.

* Change "Back to home" with a link bringing to the top of the page instead.

