[module]
  [module.hugoVersion]
    extended = true
    min = "0.95.0"

  [[module.imports]]
    path = "github.com/foo-dogsquared/hugo-theme-contentful"
  [[module.imports]]
    path = "github.com/foo-dogsquared/hugo-mod-simple-icons"
  [[module.imports]]
    path="github.com/refactoringui/heroicons"
    [[module.imports.mounts]]
        source = "optimized"
        target = "assets/svg/heroicons"

