name = "hugo-theme-more-contentful"
license = "MIT"
licenselink = "https://github.com/foo-dogsquared/hugo-theme-more-contentful/blob/master/LICENSE"
description = "A Hugo theme extending the Contentful theme to be more modern."
homepage = "https://github.com/foo-dogsquared/hugo-theme-more-contentful"
tags = [ "blog" "personal" "customizable" "minimalist" "responsive" ]
features = [ "Easy addition of custom color schemes" "Multiple theme selection" ]
min_version = "0.74"

[author]
  name = "Gabriel Arazas"
  homepage = "https://foo-dogsquared.github.io/hugo-theme-more-contentful"

