---
title: About
---

= About More Contentful

This is More Contentful, a https://gohugo.io/[Hugo] theme that builds on top of link:https://github.com/foo-dogsquared/hugo-theme-contentful[Contentful].
It aims to build more features that tries to go out of its way while letting you create your content with a nice reading interface.

With this focus, it aims both for those who want to create content and for those who are willing to get their hands dirty.
Oh, the creative side of making content and themes!

On top of what Contentful already provides, here are some features this theme provides:

* A (better) reading interface, almost the same extensible theme you know and love!
* Multiple themes with Base16 themes including the ability to set the light and dark themes.
* Focus on web accessibility and search engine optimization (SEO) including https://dev.twitter.com/cards[Twitter cards] and https://opengraphprotocol.org/[Open Graph protocol].

For those who want to extend More Contentful, link:../recipes[a dedicated post on some useful recipes] is available.
