---
title: About
---

= About Contentful


Ito ay More Contentful, ang __link:https://gohugo.io/[Hugo] theme__ na nakapatong sa link:https://github.com/foo-dogsquared/hugo-theme-contentful[Contentful].
Dahil dito, mas maraming features na naghihintay para sa mga manunulat na interestado lang sa proseso ng pagsulat.

Dahil sa mga layunin na ito, ang Contentful ay para sa mga taong gusto lang gumawa o kaya'y mga taong sabik na marumihan ang mga kamay.
O, ang malikhaing bahagi ng paggawa ng mga tema at mga kuntento!

Iilan sa mga tampok ng More Contentful, di lang mga features mula sa orihinal na tema:

* (Mas) magandang layout para sa pagbabasa.
* Mabilisang paggawa ng mga __color schemes__ mula sa __Base16 themes__ na may settings para i-set ang __light__ at __dark themes__.
* Pokus sa web accessibility at search engine optimization (SEO) kabilang ang mga https://dev.twitter.com/cards[Twitter cards] and https://opengraphprotocol.org/[Open Graph protocol].

Para sa mga gustong baguhin ang tema, link:../articles/extending-contentful[mayroon isang panulat ukol dito].
