name: Update Nix dependencies
on:
  workflow_dispatch:
  schedule:
    # This is done on a biweekly basis.
    - cron: '0 0 1,15 * *'

jobs:
  update-nix-deps:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - run: nix develop --command make update
      - id: datetime
        run: |
          echo "DATETIME=$(date '+%F')" >> "$GITHUB_OUTPUT"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "ci: update lockfile as of ${{ steps.datetime.outputs.DATETIME }}"
          delete-branch: true
          branch: update-flake-lockfile
          body: ""
          commit-message: |
            Update flake lockfile as of ${{ steps.datetime.outputs.DATETIME }}
          labels: flake-update
